language: ruby
rvm:
  - 2.3.3

sudo: false

cache:
  bundler: true
  yarn: true
  directories:
    - node_modules # NPM packages

branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

before_install:
  - nvm install 6
  - npm install -g yarn && yarn

script:
  - gulp build --prod
